### ISSUE TITLE
Work for New Horizons?

### ISSUE THREAD

**Issue by Bluefissure** [juo6442/moothumb#15]
I found this interesting project and I'm wondering whether this predictor works for the New Horizons, since I didn't find any New Horizons preset in the setting.

**Comment by juo6442** [comment]
Since we don't have enough data, the parameters for NH isn't known yet. You can use CF settings for now but there's some reported cases which are not fit to the CF pattern.

I will add exprtimental parameters for NH soon. Please report with your prices if the predictor is not working with the input.

**Comment by Bluefissure** [comment]
Thanks! I'm currently collecting data from players and will post them if necessary.
